"""
Pydantic schemas for NEXUS Phase D2: Deterministic Risk Management.

Canonical contracts:
- Monetary fields: integer cents (*_cents)
- Currency: USD
- Canonical identifiers: int (product_id, store_id)
- Explainability metadata: formula, threshold_applied, explanation
"""
from typing import List, Optional
from pydantic import BaseModel, Field


# --- Configuration Schema ---

class RiskThresholdConfigModel(BaseModel):
    assumed_snapshot_date: str = Field(..., description="Point-in-time inventory snapshot date (YYYY-MM-DD)")
    snapshot_date_is_assumed: bool = Field(..., description="Whether inventory date is an analytical assumption")
    dataset_sales_start: str = Field(...)
    dataset_sales_end: str = Field(...)
    velocity_days_baseline: float = Field(365.0)

    # Placement DOS percentiles
    placement_dos_p10_days: float = Field(...)
    placement_dos_p25_days: float = Field(...)
    placement_dos_p75_days: float = Field(...)
    placement_dos_p90_days: float = Field(...)
    placement_material_capital_cents: int = Field(...)

    # Product DOS & capital
    product_dos_p90_days: float = Field(...)
    product_material_capital_cents: int = Field(...)

    # Velocity windows
    recent_window_start: str = Field(...)
    recent_window_end: str = Field(...)
    prior_window_start: str = Field(...)
    prior_window_end: str = Field(...)
    window_days: int = Field(28)
    velocity_min_prior_units: int = Field(100)
    velocity_severe_contraction_pct: float = Field(...)
    velocity_moderate_contraction_pct: float = Field(...)
    velocity_growth_pct: float = Field(...)


# --- 1. Stockout Exposure Schemas ---

class StockoutExposureItem(BaseModel):
    product_id: int = Field(..., description="Product integer ID")
    product_name: str = Field(...)
    category: str = Field(...)
    store_id: int = Field(..., description="Store integer ID")
    store_name: str = Field(...)
    store_location: str = Field(...)
    store_city: str = Field(...)
    stock_on_hand: int = Field(0, description="Current stock on hand (strictly 0)")
    historical_units_sold: int = Field(..., description="Units sold historically in 2025")
    historical_revenue_associated_cents: int = Field(..., description="Historical revenue generated by this pair in cents")
    historical_gross_profit_associated_cents: int = Field(..., description="Historical profit generated by this pair in cents")
    currency_code: str = Field("USD")


class StockoutExposureSummary(BaseModel):
    total_placements: int = Field(..., description="Total store-product placements (14,143)")
    zero_stock_placements: int = Field(..., description="Total placements currently at zero stock (321)")
    affected_products_count: int = Field(..., description="Distinct products affected by zero stock (148)")
    affected_stores_count: int = Field(..., description="Distinct stores affected by zero stock (27)")
    affected_categories_count: int = Field(..., description="Distinct categories affected by zero stock (16)")
    historical_units_sold: int = Field(..., description="Historical 2025 units sold on current zero-stock placements (14,936)")
    historical_revenue_associated_cents: int = Field(..., description="Historical 2025 revenue associated in cents (22,884,556)")
    historical_gross_profit_associated_cents: int = Field(..., description="Historical 2025 profit associated in cents (9,855,306)")
    historical_revenue_share_pct: float = Field(..., description="Share of company total sales (2.32%)")
    currency_code: str = Field("USD")
    wording_note: str = Field(
        "Historical revenue associated with current zero-stock placements. "
        "The snapshot does not prove lost sales or unfulfilled demand."
    )


class StockoutExposureResponse(BaseModel):
    summary: StockoutExposureSummary
    top_affected_products: List[dict] = Field(default_factory=list)
    top_affected_stores: List[dict] = Field(default_factory=list)
    sample_placements: List[StockoutExposureItem] = Field(default_factory=list)


# --- 2. Inventory Pressure / Days of Supply Schemas ---

class InventoryPressureItem(BaseModel):
    product_id: int
    product_name: str
    category: str
    store_id: Optional[int] = None
    store_name: Optional[str] = None
    store_location: Optional[str] = None
    stock_on_hand: int
    annual_units_sold: int
    daily_velocity: float
    days_of_supply: Optional[float]
    coverage_tier: str
    inventory_cost_cents: int
    inventory_retail_cents: int
    currency_code: str = Field("USD")
    threshold_applied: str
    explanation: str


class InventoryPressureResponse(BaseModel):
    currency_code: str = Field("USD")
    snapshot_date: str = Field("2025-12-31")
    snapshot_date_is_assumed: bool = Field(True)
    total_placements_evaluated: int
    tier_counts: dict
    high_pressure_items: List[InventoryPressureItem] = Field(default_factory=list)
    methodology_note: str = Field(
        "Coverage tiers derived from empirical positive-stock placement percentiles: "
        "High Pressure (<=130.87d, P10), Moderate Pressure (130.87-171.76d, P25), "
        "Typical (171.76-298.64d, P75), Elevated Coverage (298.64-392.04d, P90), "
        "Slow-Moving Candidate (>392.04d). Snapshot date is assumed as Dec 31, 2025."
    )


# --- 3. Slow-Moving Inventory Schemas ---

class SlowMovingProductItem(BaseModel):
    product_id: int
    product_name: str
    category: str
    stock_units: int
    annual_units_sold: int
    average_daily_velocity: float
    days_of_supply: float
    inventory_cost_value_cents: int
    inventory_retail_value_cents: int
    currency_code: str = Field("USD")
    threshold_applied: str
    explanation: str


class SlowMovingPlacementItem(BaseModel):
    store_id: int
    store_name: str
    store_location: str
    product_id: int
    product_name: str
    category: str
    stock_on_hand: int
    annual_units_sold: int
    average_daily_velocity: float
    days_of_supply: float
    inventory_cost_value_cents: int
    currency_code: str = Field("USD")
    threshold_applied: str
    explanation: str


class SlowMovingResponse(BaseModel):
    currency_code: str = Field("USD")
    snapshot_date: str = Field("2025-12-31")
    snapshot_date_is_assumed: bool = Field(True)
    product_level_candidates_count: int
    product_level_capital_exposure_cents: int
    placement_level_candidates_count: int
    placement_level_capital_exposure_cents: int
    candidate_products: List[SlowMovingProductItem] = Field(default_factory=list)
    candidate_placements: List[SlowMovingPlacementItem] = Field(default_factory=list)
    terminology_note: str = Field(
        "Slow-Moving Inventory Exposure represents capital allocated to inventory with elevated coverage. "
        "The dataset contains no storage or financing rate metrics, and all units remain active across retail placements."
    )


# --- 4. Portfolio Revenue Concentration Schemas ---

class ConcentrationMetric(BaseModel):
    entity_type: str = Field(..., description="Products, Categories, or Stores")
    entity_count: int
    top_1_share_pct: float
    top_1_entity_name: str
    top_5_share_pct: float
    top_10_share_pct: Optional[float] = None
    hhi: float
    equal_share_hhi: float
    hhi_to_equal_ratio: float
    normalized_hhi: float
    explanation: str


class ConcentrationResponse(BaseModel):
    currency_code: str = Field("USD")
    products: ConcentrationMetric
    categories: ConcentrationMetric
    stores: ConcentrationMetric
    methodology_note: str = Field(
        "Internal Portfolio Revenue Concentration. A ratio of 1.0 represents perfectly equal "
        "revenue distribution across entities. Higher values indicate increasing concentration "
        "relative to that baseline. Products, categories, and stores are internal portfolio assets, "
        "not external market competitors in an antitrust market."
    )


# --- 5. Sales Velocity Decline Schemas ---

class SalesVelocityItem(BaseModel):
    product_id: int
    product_name: str
    category: str
    prior_28d_units: int
    recent_28d_units: int
    unit_change: int
    change_pct: Optional[float]
    prior_28d_revenue_cents: int
    recent_28d_revenue_cents: int
    revenue_change_pct: Optional[float]
    classification: str
    currency_code: str = Field("USD")
    threshold_applied: str
    explanation: str


class CategorySalesVelocityItem(BaseModel):
    category: str
    prior_28d_units: int
    recent_28d_units: int
    unit_change: int
    change_pct: float
    prior_28d_revenue_cents: int
    recent_28d_revenue_cents: int
    revenue_change_pct: float
    classification: str
    currency_code: str = Field("USD")


class CompanySalesVelocityItem(BaseModel):
    prior_28d_units: int
    recent_28d_units: int
    unit_change: int
    change_pct: float
    prior_28d_revenue_cents: int
    recent_28d_revenue_cents: int
    revenue_change_pct: float
    classification: str
    currency_code: str = Field("USD")


class SalesVelocityResponse(BaseModel):
    recent_window: str = Field("2025-12-04 to 2025-12-31")
    prior_window: str = Field("2025-11-06 to 2025-12-03")
    window_days: int = Field(28)
    company_momentum: CompanySalesVelocityItem
    categories_momentum: List[CategorySalesVelocityItem] = Field(default_factory=list)
    top_contracting_products: List[SalesVelocityItem] = Field(default_factory=list)
    top_growing_products: List[SalesVelocityItem] = Field(default_factory=list)
    methodology_note: str = Field(
        "Sales velocity compares consecutive 28-day windows. Classifications are empirical: "
        "Severe Contraction (<= -22.03%, P05), Moderate Contraction (-22.03% to -9.35%, P25), "
        "Stable (-9.35% to +11.60%, P75), Growth (>= +11.60%). Minimum prior volume floor: 100 units."
    )


# --- 6. Independent Risk Overview (No single 0-100 score) ---

class RiskOverviewDomain(BaseModel):
    domain: str
    status: str
    headline_metric: str
    detail: str
    explainability: str


class RiskOverview(BaseModel):
    currency_code: str = Field("USD")
    assumed_snapshot_date: str = Field("2025-12-31")
    snapshot_date_is_assumed: bool = Field(True)
    domains: List[RiskOverviewDomain]
    governance_note: str = Field(
        "Risk Overview provides independent, deterministic domain assessments. "
        "No single 0-100 score or arbitrary weighting is applied. No AI/LLM models calculate risk."
    )
