import React from 'react';
import { AlertTriangle, Info, Package, Store } from 'lucide-react';
import { formatUSDFromCents, formatNumber } from '../../utils/formatters';

/**
 * StockoutExposureSection
 *
 * Displays verified stockout analytics using authorized terminology only.
 * "Historical Revenue Associated" — NOT "lost revenue" or "revenue at risk".
 */
export function StockoutExposureSection({ data }) {
  if (!data) {
    return (
      <div className="rounded-xl border border-[#1f1a54]/60 bg-[#07041c]/60 p-6 text-center text-slate-400 text-sm">
        Stockout data unavailable.
      </div>
    );
  }

  const {
    zero_stock_placements = 0,
    affected_products = 0,
    affected_stores = 0,
    affected_categories = 0,
    historical_revenue_associated_cents = 0,
    historical_gross_profit_associated_cents = 0,
    sample_placements = [],
    snapshot_date,
    snapshot_date_is_assumed,
    currency_code = 'USD',
  } = data;

  const statCards = [
    {
      label: 'Zero-Stock Placements',
      value: formatNumber(zero_stock_placements),
      icon: Package,
      colorClass: 'text-rose-400',
      borderClass: 'border-rose-500/40',
      bgClass: 'bg-rose-950/20',
    },
    {
      label: 'Affected Products',
      value: formatNumber(affected_products),
      icon: Package,
      colorClass: 'text-orange-400',
      borderClass: 'border-orange-500/40',
      bgClass: 'bg-orange-950/20',
    },
    {
      label: 'Affected Stores',
      value: formatNumber(affected_stores),
      icon: Store,
      colorClass: 'text-amber-400',
      borderClass: 'border-amber-500/40',
      bgClass: 'bg-amber-950/20',
    },
    {
      label: 'Affected Categories',
      value: formatNumber(affected_categories),
      icon: Package,
      colorClass: 'text-yellow-400',
      borderClass: 'border-yellow-500/40',
      bgClass: 'bg-yellow-950/20',
    },
  ];

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="flex items-center gap-2">
        <AlertTriangle className="w-5 h-5 text-rose-400" />
        <h2 className="text-base font-semibold text-[#fbfbfe]">Stockout Exposure</h2>
        <span className="px-2 py-0.5 rounded-full text-[10px] font-semibold bg-rose-950/50 border border-rose-500/40 text-rose-300">
          {formatNumber(zero_stock_placements)} placements at zero stock
        </span>
      </div>

      {/* Stat cards */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
        {statCards.map((card) => {
          const Icon = card.icon;
          return (
            <div key={card.label} className={`rounded-xl border ${card.borderClass} ${card.bgClass} p-4`}>
              <div className={`w-7 h-7 rounded-lg bg-[#07041c]/80 flex items-center justify-center mb-2`}>
                <Icon className={`w-3.5 h-3.5 ${card.colorClass}`} />
              </div>
              <div className="text-2xl font-bold text-[#fbfbfe] leading-none mb-1">{card.value}</div>
              <div className="text-[11px] text-slate-400">{card.label}</div>
            </div>
          );
        })}
      </div>

      {/* Historical Revenue Associated */}
      <div className="rounded-xl border border-[#2f27ce]/30 bg-[#0d0a30]/80 p-4 grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <div className="text-[10px] text-slate-400 uppercase tracking-wider mb-1 flex items-center gap-1">
            Historical Revenue Associated
            <span className="group relative cursor-help">
              <Info className="w-3 h-3 text-slate-500 hover:text-slate-300" />
              <span className="absolute bottom-5 left-0 z-10 hidden group-hover:block w-64 bg-[#07041c] border border-[#1f1a54] text-[10px] text-slate-300 rounded-lg p-2.5 leading-relaxed shadow-xl">
                This is historical 2025 revenue generated by store-product pairs that currently have
                zero stock. It is not a measure of lost sales.
              </span>
            </span>
          </div>
          <div className="text-xl font-bold text-[#fbfbfe]">
            {formatUSDFromCents(historical_revenue_associated_cents)}
          </div>
          <div className="text-[10px] text-slate-400 mt-1">
            Historical 2025 revenue from affected store-product pairs · {currency_code}
          </div>
        </div>
        <div>
          <div className="text-[10px] text-slate-400 uppercase tracking-wider mb-1">
            Historical Gross Profit Associated
          </div>
          <div className="text-xl font-bold text-[#fbfbfe]">
            {formatUSDFromCents(historical_gross_profit_associated_cents)}
          </div>
          <div className="text-[10px] text-slate-400 mt-1">
            Historical 2025 gross profit from affected store-product pairs · {currency_code}
          </div>
        </div>
      </div>

      {/* Disclosure note */}
      <div className="rounded-lg border border-amber-500/30 bg-amber-950/10 px-4 py-2.5 text-[11px] text-amber-200/80 flex items-start gap-2">
        <Info className="w-3.5 h-3.5 text-amber-400 shrink-0 mt-0.5" />
        <span>
          <strong>Terminology note:</strong> "Historical Revenue Associated" refers to 2025 revenue
          generated by store-product pairs that currently carry zero stock. This snapshot does not
          prove lost demand — the revenue may have been captured before stockout occurred.
        </span>
      </div>

      {/* Sample placements table */}
      {sample_placements.length > 0 && (
        <div className="space-y-2">
          <div className="text-xs font-semibold text-slate-300">Sample Zero-Stock Placements</div>
          <div className="rounded-xl border border-[#1f1a54]/60 overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full text-xs">
                <thead>
                  <tr className="border-b border-[#1f1a54]/60 bg-[#07041c]/80">
                    <th className="px-3 py-2.5 text-left text-[10px] text-slate-400 font-semibold uppercase tracking-wider">Product ID</th>
                    <th className="px-3 py-2.5 text-left text-[10px] text-slate-400 font-semibold uppercase tracking-wider">Product</th>
                    <th className="px-3 py-2.5 text-left text-[10px] text-slate-400 font-semibold uppercase tracking-wider">Store</th>
                    <th className="px-3 py-2.5 text-left text-[10px] text-slate-400 font-semibold uppercase tracking-wider">Category</th>
                    <th className="px-3 py-2.5 text-right text-[10px] text-slate-400 font-semibold uppercase tracking-wider">Historical Revenue</th>
                  </tr>
                </thead>
                <tbody>
                  {sample_placements.slice(0, 10).map((p, i) => (
                    <tr key={`${p.product_id}-${p.store_id}`} className={`border-b border-[#1f1a54]/30 ${i % 2 === 0 ? 'bg-[#050315]/40' : ''} hover:bg-[#130f3b]/30 transition-colors`}>
                      <td className="px-3 py-2 text-[#a5a0ff] font-mono">{p.product_id}</td>
                      <td className="px-3 py-2 text-slate-200 max-w-[160px] truncate">{p.product_name}</td>
                      <td className="px-3 py-2 text-slate-300">#{p.store_id}</td>
                      <td className="px-3 py-2 text-slate-400">{p.category}</td>
                      <td className="px-3 py-2 text-right font-mono text-emerald-300">
                        {formatUSDFromCents(p.historical_revenue_associated_cents)}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}

      {snapshot_date_is_assumed && (
        <div className="text-[10px] text-slate-500">
          Snapshot: {snapshot_date} (assumed) · {currency_code}
        </div>
      )}
    </div>
  );
}
